[project]
name = "pinel-localizer"
authors = [
  {name = "Christophe Pallier", email = "christophe@pallier.org"},
  {name = "Antonio Moreno", email = "antonio.moreno@inserm.fr"},
  {name = "Isabelle Denghien", email = "isabelle.denghien@inserm.fr"},
  {name = "Philippe Pinel"}
  ]
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "expyriment>=1.0.0",
    "npyscreen>=4.10.5",
]

[tool.setuptools]
py-modules = []